accounts/urls.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from django.urls import path
from accounts import views as account_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', account_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('profile/', account_views.profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'), name='reset-password'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('toggle-registrations/', account_views.toggle_registrations, name='toggle-registrations'),
    path('test-server-error/', account_views.test_server_error, name='test-server-error')
]

pc_calculator/urls.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from os import name
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from pc_calculator import views, utils

app_name = "pc-calc"

urlpatterns = [
    path('api/program-outcome-results/', views.ProgramOutcomeResultList.as_view(), name='api-poresults'),
    path('api/students/', views.StudentList.as_view(), name='api-students'),
    path('api/program-outcomes/', views.ProgramOutcomeList.as_view(), name='api-po'),

    path('report/', views.report_view, name='report'),
    path('report/progress/<uuid>/', views.get_task_progress, name='task-progress'),
    path('report/download/<uuid>/<str:file_type>/', views.get_task_data, name='task-data'),
    path('upload/', views.upload_program_outcome_file, name='upload'),
    path('', views.upload_program_outcome_file, name='home'),
    path('export/', views.export, name='export'),
    path('export-diff/', views.export_diff, name='export-diff'),
    path('course-report/', views.course_report, name='course-report'),
    path('changelog/', views.changelog, name='changelog'),
    path('logs/', views.debug_logs, name='logs'),
    path('manage/', views.ProgramOutcomeFileListView.as_view(), name='manage'),
    path('manage/<int:pk>/update/', views.ProgramOutcomeFileUpdateView.as_view(), name='update'),
    path('manage/<int:pk>/delete/', views.ProgramOutcomeFileDeleteView.as_view(), name='delete'),
    path('manage/<int:pk>/delete-file-only/', views.ProgramOutcomeFileDeleteOnlyFileView.as_view(), name='delete-file-only'),

    path('upload/students/', views.populate_students, name='update-students'),
    path('upload/excempt-students/', views.handle_excempt_students, name='update-excempt-students'),
    path('recalculate-all-pos/', views.recalculate_all_pos, name='recalculate-all-pos'),
    path('create-backup-snapshot/', views.dump_pclink, name='create-backup-snapshot'),
    path('restore-pclink/', views.restore_pclink, name='restore-pclink'),
    path('remove-duplicates/', views.remove_duplicates, name='remove-duplicates'),
    path('upload/courses/', views.populate_courses_and_pos, name='populate-courses'),
    # path('upload/program-outcomes/', utils.populate_program_outcomes),
]

urlpatterns = format_suffix_patterns(urlpatterns)

pc_link_rest/urls.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from django.contrib import admin
from django.urls import path, include, re_path
from accounts import views as account_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pc_calculator.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pc_calculator/views.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from django.forms import utils
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpResponse, FileResponse, JsonResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import mail
from django.conf import settings
from django.core.management import call_command
from django.db.models import Count, Max
from django.core.paginator import Paginator
from django_celery_results.models import TaskResult

from rest_framework import generics
from rest_framework.permissions import IsAuthenticated

from pc_calculator.models import *
from pc_calculator.serializers import *
from pc_calculator.forms import *
from pc_calculator.utils import *
from pc_calculator.tasks import export_task, export_diff_task

from itertools import chain
import pandas as pd
import datetime
import time
import logging
import io
import os
import bz2
import re
from celery.utils.serialization import b64encode, b64decode

logger = logging.getLogger('pc_link_custom_logger')

class ProgramOutcomeResultList(generics.ListAPIView):
    queryset = ProgramOutcomeResult.objects.all()
    serializer_class = ProgramOutcomeResultSerializer
    permission_classes = [IsAuthenticated]


class StudentList(generics.ListAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer
    permission_classes = [IsAuthenticated]


class ProgramOutcomeList(generics.ListAPIView):
    queryset = ProgramOutcome.objects.all()
    serializer_class = ProgramOutcomeSerializer
    permission_classes = [IsAuthenticated]

#############################################################

class ProgramOutcomeFileListView(LoginRequiredMixin, generic.ListView):
    model = ProgramOutcomeFile
    template_name = 'pc_calculator/manage.html'
    paginate_by = 10

    def get_queryset(self):
        if not self.request.user.is_superuser:
            return ProgramOutcomeFile.objects.filter(user=self.request.user).order_by('-date_uploaded')
        return ProgramOutcomeFile.objects.order_by('-date_uploaded')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['semesters'] = Semester.objects.all()
        return context


class ProgramOutcomeFileUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = ProgramOutcomeFile
    fields = ['semester', 'course', 'pc_file']
    template_name = 'pc_calculator/update.html'
    success_url = reverse_lazy('pc-calc:manage')

    def form_valid(self, form):
        semester = form.cleaned_data['semester']
        course = form.cleaned_data['course']
        pc_file = form.cleaned_data['pc_file']
        old_name = self.object.pc_file.name
        
        response = super().form_valid(form)

        os.remove(os.path.join(os.path.dirname(self.object.pc_file.path), old_name))

        upload_result = handle_upload(self.request, course.code, semester.id, pc_file, self.object)

        if upload_result[0]:
            messages.success(self.request, 'Program Outcome file is successfuly updated.')
        else:
            messages.warning(self.request, 'No student from the department exists in the uploaded file.')

        return response


class ProgramOutcomeFileDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = ProgramOutcomeFile
    success_url = reverse_lazy('pc-calc:manage')
    template_name = 'pc_calculator/confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object = self.get_object()
        context['por_objects'] = ProgramOutcomeResult.objects.filter(semester=self.object.semester, course=self.object.course)
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()

        po_results = ProgramOutcomeResult.objects.filter(semester=self.object.semester, course=self.object.course)
        if os.path.exists(os.path.join(settings.MEDIA_ROOT, str(self.object.pc_file))):
            os.remove(os.path.join(settings.MEDIA_ROOT, str(self.object.pc_file)))
        po_results.delete()

        return super().delete(request, *args, **kwargs)


class ProgramOutcomeFileDeleteOnlyFileView(LoginRequiredMixin, generic.DeleteView):
    model = ProgramOutcomeFile
    success_url = reverse_lazy('pc-calc:manage')
    template_name = 'pc_calculator/confirm_delete.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()

        if os.path.exists(os.path.join(settings.MEDIA_ROOT, str(self.object.pc_file))):
            os.remove(os.path.join(settings.MEDIA_ROOT, str(self.object.pc_file)))

        return super().delete(request, *args, **kwargs)


@login_required
def report_view(request):
    """Exports the user uploaded entries filtered by the given parameters."""
    export_report_form = ExportReportForm(request.POST or None)
    export_diff_report_form = ExportDiffReportForm(request.POST or None)

    context = {
        'export_form': export_report_form,
        'export_diff_form': export_diff_report_form
    }

    if request.method == 'POST':
        if export_report_form.is_valid():
            logger.info(f'Export requested by {request.user}.')
            file_type = export_report_form.cleaned_data['export_type']
            semesters = export_report_form.cleaned_data['semesters']
            curriculum = export_report_form.cleaned_data['curriculum']
            logger.debug(f'Exporting for semesters {semesters} for curriculum {curriculum}.')
            async_result = export_task.apply_async((semesters, curriculum), serializer='pickle')
            context['task_id'] = async_result.task_id
            context['file_type'] = file_type
        elif export_diff_report_form.is_valid():
            logger.info(f'Export diff requested by {request.user}.')
            file_type = export_diff_report_form.cleaned_data['export_type']
            first_semesters = export_diff_report_form.cleaned_data['first_semesters']
            second_semesters = export_diff_report_form.cleaned_data['second_semesters']
            curriculum = export_diff_report_form.cleaned_data['curriculum']
            logger.debug(f'Exporting diff for semesters {first_semesters} and {second_semesters} for curriculum {curriculum}.')
            async_result = export_diff_task.apply_async((first_semesters, second_semesters, curriculum), serializer='pickle')
            context['task_id'] = async_result.task_id
            context['file_type'] = file_type

    return render(
        request,
        'pc_calculator/report.html',
        context
    )


@login_required
def get_task_progress(request, uuid):
    try:
        result = TaskResult.objects.filter(task_id=uuid).first()
        logger.debug(f'Sending task progress: {result.status}')

        if result.status == 'FAILURE':
            logger.error(result)

        response_data = {
            'status': result.status,
        }
    except:
        response_data = {
            'status': 'PENDING',
        }

    return JsonResponse(response_data)


@login_required
def get_task_data(request, uuid, file_type):
    logger.debug(f'get_task_data is called for uuid: {uuid} and file_type: {file_type}.')

    result = TaskResult.objects.filter(task_id=uuid).first()

    report_df = pd.read_pickle(io.BytesIO(b64decode(result.result)))

    logger.debug(f'Found report_df with columns {report_df.columns.tolist()}.')

    if file_type == 'xlsx':
        xlsx_buffer = io.BytesIO()
        with pd.ExcelWriter(xlsx_buffer) as xlwriter:
            report_df.to_excel(xlwriter)
        xlsx_buffer.seek(0)
        response = HttpResponse(xlsx_buffer.read(), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response["Content-Disposition"] = 'attachment; filename="report.xlsx"'
        logger.debug('XLSX response is prepared.')
    elif file_type == 'csv':
        csv_buffer = io.StringIO()
        report_df.to_csv(csv_buffer, index=True)
        csv_buffer.seek(0)
        response = HttpResponse(csv_buffer.read(), content_type = 'text/csv')
        response["Content-Disposition"] = 'attachment; filename="report.csv"'
        logger.debug('CSV response is prepared.')

    return response


@login_required
@user_passes_test(lambda user: user.is_superuser)
def debug_logs(request):
    with open(settings.BASE_DIR / 'persist' / 'pc-link.log', 'r') as logs_f:
        raw_log_entries = logs_f.readlines()
    
    raw_log_entries = list(reversed(raw_log_entries))

    log_entries = list()
    for row in raw_log_entries:
        regex_result = re.search(r'\[(\d{2}\/[A-Z][a-z]{2}\/\d{4} \d{2}:\d{2}:\d{2}) (INFO|DEBUG|WARNING|ERROR|FATAL)\]  (.*)', row)
        if regex_result is not None:
            capture_groups = regex_result.groups()
            log_time = datetime.datetime.strptime(capture_groups[0], '%d/%b/%Y %H:%M:%S')
            log_entry = {
                'date': log_time,
                'level': capture_groups[1],
                'message': capture_groups[2]
            }

pc_calculator/templates/pc_calculator/change_log.html
{% extends 'dashboard-base.html' %}
{% load static %}
{% block page_title %}Changelog{% endblock %}
{% block content %}

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Date</th>
            <th scope="col">Author</th>
            <th scope="col">Commit</th>
            <th scope="col">Commit Message</th>
        </tr>
    </thead>
    <tbody>
        {% for commit in page_obj %}
            {% if forloop.first and not page_obj.has_previous %}
                <tr class="table-primary">
                    <th scope="row">{{ forloop.counter0|add:page_obj.start_index }}</th>
                    <td>{{ commit.date }}</td>
                    <td>{{ commit.author }}</td>
                    <td><a href="{{ commit.commit_link }}">{{ commit.commit_id }}</a></td>
                    <td><b>NEW!!! {{ commit.commit_message }}</b></td>
                </tr>
            {% else %}
                <tr>
                    <th scope="row">{{ forloop.counter0|add:page_obj.start_index }}</th>
                    <td>{{ commit.date }}</td>
                    <td>{{ commit.author }}</td>
                    <td><a href="{{ commit.commit_link }}">{{ commit.commit_id }}</a></td>
                    <td>{{ commit.commit_message }}</td>
                </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.number|add:"-1" }}</a></li>
        {% endif %}
        <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.number|add:"1" }}</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
        {% endif %}
    </ul>
</nav>

{% endblock %}

pc_calculator/templates/pc_calculator/confirm_delete.html
{% extends 'dashboard-base.html' %}
{% load static %}
{% block page_title %}Confirm Deletion{% endblock %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <h3>Are you sure you want to delete {{ object.filename }}?</h3>
    <p>This will also delete the following Program Outcome Result records:</p>
    <ul>
        {% for por in por_objects %}
            <li>{{ por }}</li>
        {% endfor %}
    </ul>
    <p>Total of {{ por_objects|length }} records will be deleted.</p>
    <button type="submit" class="btn btn-outline-danger">Yes, Delete</button>
    <a class="btn btn-outline-secondary" href="{% url 'pc-calc:manage' %}">Cancel</a>
</form>

{% endblock %}

pc_calculator/templates/pc_calculator/help.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>PÇ-Link User Manual</h1>

<div class="alert alert-warning" role="alert">
    <i class="fas fa-exclamation-triangle"></i> <strong>Any found bug or suspicious behaviour should be reported on 
    <a href="http://bugs.toliga.com/">http://bugs.toliga.com/</a> as a new issue.</strong> This process is necessary to debug and 
    keep the software healthy, available, and working throughout the entire alpha-beta period.
</div>

<p>PÇ-Link application is a web application for easy calculation and management of students’ program outcome resuls and 
averages. The current hosting server is placed in the Frankfurt/Germany, and the VPS service is provided by 
DigitalOcean. The source code is located in a private repository on Atlassian BitBucket.</p>

<p>This manual defines the basic interactions with the PÇ-Link application.</p>

<ol>
    <li>
        <p>When a user enters the <a href="http://toliga.com/se/">http://toliga.com/se/</a> or 
        <a href="http://toliga.com/cmpe/">http://toliga.com/cmpe/</a>, the page shown in Figure 1 is presented. This page is 
        the main page of the application.
        
        <img src="{% static 'pc_calculator/img/login_page.png' %}" class="img-fluid"></p>
        
        <p>In the main page, several options/functions are served depending on what the user want to do.</p>

        <ul>
            <li><strong>Upload Course Outcome File:</strong> <u>Login required.</u> This option redirects you to the CSV upload page.</li>
            <li><strong>Create Report:</strong> <u>Login required.</u> This option redirects you to the report creationg page. 
            Also you can download a CSV file containing all students with their respected course outcome averages.</li>
            <li><strong>Manage Uploaded Files:</strong> <u>Login required.</u> This option redirects you to a page which you can 
            mange the previously uploaded files. You can delete or edit the existing uploads.</li>
            <li><strong>Help:</strong> The online version of the PÇ-Link User Manual document.</li>
            <li><strong>Login:</strong> Login page.</li>
            <li><strong>Register:</strong> Registration page.</li>
        </ul>
    </li>
    <li>
        <p>Users must be logged in to the system to make uploads or reporting or any change.  The registration process 
        is started by clicking to the Register button from top navigation bar. This button redirects to a registration 
        page shown in Figure 2.</p>

        <img src="{% static 'pc_calculator/img/register_page.png' %}" class="img-fluid"></p>

        <p>All fields are required. <strong>Note that, this page will be disabled when all previously defined users are 
        registered.</strong></p>
    </li>
    <li>
        <p>After the registration process, users will be redirected to a page shown in Figure 1. Login page is 
        straightforward. When users log into the system, they can interact all of the defined functionality.</p>

        <p><strong><em>There is no SSL/TLS encrpytion in the site traffic. Users should be careful about their choice of 
        password since the hash of the password can be stolen with the man-in-the-middle attacks.</em></strong></p>
    </li>
    <li>
        <p>A logged in user is automatically redirected to course outcome upload page as shown in Figure 3.</p>

        <img src="{% static 'pc_calculator/img/uploads_page.png' %}" class="img-fluid"></p>

        <p>In this page, all form elements are required. User must choose the related course with the CSV file from 
        <strong>Select a course*</strong> combo box, the related semester from <strong>Select a semester:*</strong> combo box1 and upload 
        the CSV file from the <strong>Upload the PÇ File:*</strong> file upload field.</p>

        <p>The CSV file has to be in a certain and consistent format. The format structure is explained in the page 
        itself and is quoted below.</p>

        <blockquote class="blockquote">
            <p>The course outcome file should be in .csv format. You can find an example .csv file opened as a 
            spreadsheet on the side. The first column <u>student_id</u> represents the <strong>ID</strong> of the student, the 
            second column <u>name</u> represents the <strong>name and surname</strong> of the student, and the remaining columns 
            are the course outcomes (PÇ1, PÇ2, etc.) of the course. <strong>The names of course outcome columns should be the 
            exact codes (case-sensitive) of the PÇs (e.g. PÇ1, PÇ7a, PÇ7b, etc.).</strong></p>
        </blockquote>

        <p>When the user presses the upload button, CSV file is sent to the server. There is no need to seperate the 
        students of different departments. PÇ-Link can differentiate the students from CMPE and SE depending on the 
        uploaded site. This process is automatically handled.</p>
    </li>
    <li>
        <p>A user can create filtered reports and export unfiltered reports by clicking the Create Report button from 
        the top naviagtion bar.</p>

        <img src="{% static 'pc_calculator/img/report_page.png' %}" class="img-fluid"></p>

        <p>In this page, a user can create and display reports filtered by the filtering options shown in right side of 
        Figure 5. Notice that, these filters are not going to be applied when exporting a CSV or XLSX.</p>

        <p>Users can choose the details of the record they want to create and give a overall course outcome value. If 
        the record already exists, then the existing record is updated, otherwise a new record is created.</p>
    </li>
    <li>
        <p>Bug reports and other issues can be created in the following link by self-registered reporters.</p>
        <p class="text-center"><a href="http://bugs.toliga.com/">http://bugs.toliga.com/</a></p>
        <p>For all other problems with the system, send an email to 
        <a href="mailto:tolga.ustunkok@atilim.edu.tr">tolga.ustunkok@atilim.edu.tr</a>.</p>
    </li>
</ol>

{% endblock %}

pc_calculator/templates/pc_calculator/manage.html
{% extends 'dashboard-base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_title %}Manage Uploaded Files{% endblock %}
{% block content %}
<div class="row">
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">File Name</th>
                    <th scope="col">Course</th>
                    <th scope="col">Semester</th>
                    <th scope="col">Uploaded By</th>
                    <th scope="col">Upload Date</th>
                    <th scope="col">Operation</th>
                </tr>
            </thead>
            <tbody>
                {% for file in page_obj %}
                <tr>
                    <td>{{ file.filename|truncatechars:30 }}</td>
                    <td>{{ file.course }}</td>
                    <td>{{ file.semester }}</td>
                    <td>{{ file.user.username|truncatechars:15 }}</td>
                    <td>{{ file.date_uploaded }}</td>
                    <td><a href="{% url 'pc-calc:update' file.id %}"><i class="far fa-edit"></i></a> | <a
                            href="{% url 'pc-calc:delete-file-only' file.id %}"><i
                                class="fas fa-folder-minus"></i></a> | <a
                            href="{% url 'pc-calc:delete' file.id %}"><i class="far fa-trash-alt"></i></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.number|add:"-1" }}</a></li>
                {% endif %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.number|add:"1" }}</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last
                        &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col">
        <form class="form-inline" action="{% url 'pc-calc:course-report' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label>Show uploaded status of courses for the semester:&nbsp;</label>
                <select class="form-control" name="semester">
                    {% for sem in semesters %}
                    <option value="{{ sem.id }}">{{ sem }}</option>
                    {% endfor %}
                </select>
            </div>
            <button class="btn btn-secondary" type="submit">Show</button>
        </form>
    </div>
</div>
{% endblock %}

pc_calculator/templates/pc_calculator/report.html
{% extends 'dashboard-base.html' %}
{% load crispy_forms_tags %}
{% load my_tags %}
{% block page_title %}Export Report{% endblock %}
{% block content %}

<div class="row">
    <div class="col border rounded p-3 m-2">
        <h5>Export Report</h5>
        <hr>
        <form id="exportForm" method="POST">
            {% csrf_token %}
            {{ export_form|crispy }}
            <button class="btn btn-primary downloadButton" type="submit">Download</button>
            <button class="btn btn-primary loadingButton" type="button" disabled>
                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                Preparing Report...
            </button>
        </form>

    </div>
    <div class="col border rounded p-3 m-2">
        <h5>Export Diff</h5>
        <hr>
        <form id="exportDiffForm" method="POST">
            {% csrf_token %}
            {{ export_diff_form|crispy }}
            <button class="btn btn-primary downloadButton" type="submit">Download</button>
            <button class="btn btn-primary loadingButton" type="button" disabled>
                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                Preparing Report...
            </button>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    var loadingBtns = $('.loadingButton');
    var downloadBtns = $('.downloadButton');

    {% if task_id %}
    downloadBtns.hide();
    loadingBtns.show();
    var intervalId = window.setInterval( function () {
        $.get({
            url: '{% url "pc-calc:task-progress" task_id %}',
            success: function (data) {

                if (data.status === 'SUCCESS') {
                    window.location.href = '{% url "pc-calc:task-data" task_id file_type %}';
                    clearInterval(intervalId);
                    loadingBtns.hide();
                    downloadBtns.show();
                } else if (data.status === 'FAILURE') {
                    alert("This is the point that everything is collapsed and Tolga does not know about that. Please inform him immediately!!!");
                    clearInterval(intervalId);
                    loadingBtns.hide();
                    downloadBtns.show();
                }
            }
        });
    }, 1000);
    {% else %}
    loadingBtns.hide();
    {% endif %}
</script>
{% endblock %}

pc_calculator/templates/pc_calculator/update.html
{% extends 'dashboard-base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% block page_title %}Update Record{% endblock %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Update</button>
</form>

{% endblock %}