accounts/urls.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from django.urls import path
from accounts import views as account_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', account_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('profile/', account_views.profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'), name='reset-password'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('toggle-registrations/', account_views.toggle_registrations, name='toggle-registrations'),
    path('test-server-error/', account_views.test_server_error, name='test-server-error')
]

pc_calculator/urls.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from os import name
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from pc_calculator import views, utils

app_name = "pc-calc"

urlpatterns = [
    path('api/program-outcome-results/', views.ProgramOutcomeResultList.as_view(), name='api-poresults'),
    path('api/students/', views.StudentList.as_view(), name='api-students'),
    path('api/program-outcomes/', views.ProgramOutcomeList.as_view(), name='api-po'),

    path('report/', views.report_view, name='report'),
    path('report/progress/<uuid>/', views.get_task_progress, name='task-progress'),
    path('report/download/<uuid>/<str:file_type>/', views.get_task_data, name='task-data'),
    path('upload/', views.upload_program_outcome_file, name='upload'),
    path('', views.upload_program_outcome_file, name='home'),
    path('export/', views.export, name='export'),
    path('export-diff/', views.export_diff, name='export-diff'),
    path('course-report/', views.course_report, name='course-report'),
    path('changelog/', views.changelog, name='changelog'),
    path('logs/', views.debug_logs, name='logs'),
    path('manage/', views.ProgramOutcomeFileListView.as_view(), name='manage'),
    path('manage/<int:pk>/update/', views.ProgramOutcomeFileUpdateView.as_view(), name='update'),
    path('manage/<int:pk>/delete/', views.ProgramOutcomeFileDeleteView.as_view(), name='delete'),
    path('manage/<int:pk>/delete-file-only/', views.ProgramOutcomeFileDeleteOnlyFileView.as_view(), name='delete-file-only'),

    path('upload/students/', views.populate_students, name='update-students'),
    path('upload/excempt-students/', views.handle_excempt_students, name='update-excempt-students'),
    path('recalculate-all-pos/', views.recalculate_all_pos, name='recalculate-all-pos'),
    path('create-backup-snapshot/', views.dump_pclink, name='create-backup-snapshot'),
    path('restore-pclink/', views.restore_pclink, name='restore-pclink'),
    path('remove-duplicates/', views.remove_duplicates, name='remove-duplicates'),
    path('upload/courses/', views.populate_courses_and_pos, name='populate-courses'),
    # path('upload/program-outcomes/', utils.populate_program_outcomes),
]

urlpatterns = format_suffix_patterns(urlpatterns)

pc_link_rest/urls.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from django.contrib import admin
from django.urls import path, include, re_path
from accounts import views as account_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pc_calculator.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from django.db import models
from pc_calculator.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


    def __str__(self):
        return f'{self.user.username} Profile'

accounts/forms.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from django import forms
from pc_calculator.models import User
from accounts.models import Profile
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

accounts/views.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from accounts.forms import *
from pc_calculator.forms import StudentBulkUploadForm, RestoreBackupForm, CoursePOBulkUploadForm
from django.conf import settings

def register(request):
    with open(settings.BASE_DIR / 'persist/registration_state.txt', 'r') as reg_f:
        reg_enabled = bool(int(reg_f.read()))

    if reg_enabled:
        if request.method == 'POST':
            user_creation_form = UserRegisterForm(request.POST)
            if user_creation_form.is_valid():
                user_creation_form.save()
                messages.success(request, 'Your account has been created. You are now able to log in.')
                return redirect('login')
        else:
            user_creation_form = UserRegisterForm()
        return render(request, 'accounts/register.html', {'form': user_creation_form})
    else:
        messages.warning(request, 'Registrations to PÇ-Link are closed.')
        return redirect('login')


@login_required
@staff_member_required
def toggle_registrations(request):
    with open(settings.BASE_DIR / 'persist/registration_state.txt', 'r+') as reg_f:
        reg_enabled = bool(int(reg_f.read()))
        reg_f.seek(0)
        reg_f.write(str(int(not reg_enabled)))
        messages.success(request, 'Registration status: ' + str(not reg_enabled))

    return redirect('profile')

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your profile is updated.')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
        stu_bulk_form = StudentBulkUploadForm()
        excempt_stu_form = StudentBulkUploadForm()
        course_bulk_form = CoursePOBulkUploadForm()
        snapshot_form = RestoreBackupForm()
    
    try:
        with open(settings.BASE_DIR / 'persist' / 'registration_state.txt', 'r') as reg_f:
            reg_enabled = bool(int(reg_f.read()))
    except:
        with open(settings.BASE_DIR / 'persist' / 'registration_state.txt', 'w') as reg_f:
            reg_f.write('1')
            reg_enabled = True
    
    context = {
        'u_form': u_form,
        'p_form': p_form,
        'stu_bulk_form': stu_bulk_form,
        'excempt_stu_form': excempt_stu_form,
        'reg_status': reg_enabled,
        'snapshot_form': snapshot_form,
        'course_bulk_form': course_bulk_form,
    }

    return render(request, 'accounts/profile.html', context)


@login_required
@staff_member_required
def test_server_error(request):
    return redirect('non-existing-page')

accounts/templates/accounts/login.html
{% extends 'dashboard-base.html' %}
{% load crispy_forms_tags %}

{% block page_title %}Login{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-8">
            <div class="content-section">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Login</button>
                        <small class="text-muted">
                            <a class="ml-2" href="{% url 'reset-password' %}">Forgot password?</a>
                        </small>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Need an account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
                    </small>
                </div>
            </div>
        </div>
        <div class="col-4"></div>
    </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'dashboard-base.html' %}
{% block page_title %}Logout Completed{% endblock %}
{% block content %}
<h2>You have been logged out.</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'dashboard-base.html' %}
{% load crispy_forms_tags %}
{% block page_title %}Reset Completed{% endblock %}
{% block content %}
    <div class="row">
        <div class="col">
            <h3>Your password has been reset. You can now <a href="{% url 'login' %}">login</a>.</h3>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'dashboard-base.html' %}
{% load crispy_forms_tags %}
{% block page_title %}Confirm Password Reset{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="content-section">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom  mb-4">Confirm New Password</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Confirm Password</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'dashboard-base.html' %}
{% load crispy_forms_tags %}
{% block page_title %}Reset Done{% endblock %}
{% block content %}
    <div class="row">
        <div class="col">
            <h3>We have sent you an email to confirm your password reset.</h3>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_form.html
{% extends 'dashboard-base.html' %}
{% load crispy_forms_tags %}

{% block page_title %}Password Reset{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="content-section">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom  mb-4">Reset Password</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Reset Password</button>
                        <small class="text-muted">
                            <a class="ml-2" href="{% url 'login' %}">Already have an account?</a>
                        </small>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'dashboard-base.html' %}
{% load crispy_forms_tags %}

{% block page_title %}Profile{% endblock %}
{% block content %}

<div class="row">
    <div class="col-4 text-center">
        <img class="img-thumbnail" src="{{ user.profile.image.url }}" width="200px" height="200px">
        <h2>{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
        <p><a href="{% url 'reset-password' %}">Reset Password</a></p>
        {% if user.is_superuser %}
        <div class="card border-danger text-center mx-auto" style="max-width: 18rem;">
            <div class="card-body text-danger">
                <h5 class="card-title">Danger Zone</h5>
                <p class="card-text"><a class="btn btn-danger"
                        onclick="return confirm('This is a destructive process and will take several minutes to complete. Do you want to continue?')"
                        href="{% url 'pc-calc:recalculate-all-pos' %}">Rebuild PO Results Table</a></p>
                <p class="card-text"><a class="btn btn-danger"
                        onclick="return confirm('This is a destructive process and will remove duplicate records from the database. Do you want to continue?')"
                        href="{% url 'pc-calc:remove-duplicates' %}">Remove Duplicate PO Results</a></p>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="col-8">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-primary btn-sm" type="submit">Update Profile</button>
            </div>
        </form>
        {% if user.is_staff %}
        <div class="row">
            <div class="col-4">
                <form method="POST" enctype="multipart/form-data" action="{% url 'pc-calc:update-students' %}">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Update Student Information</legend>
                        {{ stu_bulk_form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-primary btn-sm" type="submit">Update Students</button>
                    </div>
                </form>
            </div>
            <div class="col-4">
                <form method="POST" enctype="multipart/form-data" action="{% url 'pc-calc:update-excempt-students' %}">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Upload Excempt Students</legend>
                        {{ stu_bulk_form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-primary btn-sm" type="submit">Update Excempt Students</button>
                    </div>
                </form>
            </div>
            <div class="col-4">
                <form method="POST" enctype="multipart/form-data" action="{% url 'pc-calc:populate-courses' %}">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Upload Courses</legend>
                        {{ course_bulk_form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-primary btn-sm" type="submit">Update Courses and POs</button>
                    </div>
                </form>
            </div>
        </div>
        
        
        {% endif %}
        {% if user.is_superuser %}
        <h4 class="border-bottom  mb-4">Maintenance</h4>
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td><a href="#" style="cursor: not-allowed;">Set Maintenance Mode</a></td>
                    <td>Toggle Registrations: <input id="toggle-reg" type="checkbox" {% if reg_status == True %}checked{% endif %} data-toggle="toggle" data-onstyle="success"></td>
                    <td><a href="{% url 'test-server-error' %}">Test Server Error</a></td>
                </tr>
                <tr>
                    <td><a href="{% url 'pc-calc:create-backup-snapshot' %}">Create Backup Snapshot</a></td>
                    <td>
                        <form method="POST" action="{% url 'pc-calc:restore-pclink' %}" enctype="multipart/form-data"
                            id="snapshot-form">{% csrf_token %}{{ snapshot_form|crispy }}</form>
                    </td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block script %}
<script>
    document.getElementById("id_snapshot_file").onchange = function () {
        document.getElementById("snapshot-form").submit();
    };

    $(function () {
        $('#toggle-reg').change(function () {
            $.ajax("{% url 'toggle-registrations' %}");
        })
    });
</script>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'dashboard-base.html' %}
{% load crispy_forms_tags %}
{% block page_title %}Register{% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="">Sign In</a>
            </small>
        </div>
    </div>
{% endblock %}