accounts/urls.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from django.urls import path
from accounts import views as account_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', account_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('profile/', account_views.profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'), name='reset-password'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('toggle-registrations/', account_views.toggle_registrations, name='toggle-registrations'),
    path('test-server-error/', account_views.test_server_error, name='test-server-error')
]

pc_calculator/urls.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from os import name
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from pc_calculator import views, utils

app_name = "pc-calc"

urlpatterns = [
    path('api/program-outcome-results/', views.ProgramOutcomeResultList.as_view(), name='api-poresults'),
    path('api/students/', views.StudentList.as_view(), name='api-students'),
    path('api/program-outcomes/', views.ProgramOutcomeList.as_view(), name='api-po'),

    path('report/', views.report_view, name='report'),
    path('report/progress/<uuid>/', views.get_task_progress, name='task-progress'),
    path('report/download/<uuid>/<str:file_type>/', views.get_task_data, name='task-data'),
    path('upload/', views.upload_program_outcome_file, name='upload'),
    path('', views.upload_program_outcome_file, name='home'),
    path('export/', views.export, name='export'),
    path('export-diff/', views.export_diff, name='export-diff'),
    path('course-report/', views.course_report, name='course-report'),
    path('changelog/', views.changelog, name='changelog'),
    path('logs/', views.debug_logs, name='logs'),
    path('manage/', views.ProgramOutcomeFileListView.as_view(), name='manage'),
    path('manage/<int:pk>/update/', views.ProgramOutcomeFileUpdateView.as_view(), name='update'),
    path('manage/<int:pk>/delete/', views.ProgramOutcomeFileDeleteView.as_view(), name='delete'),
    path('manage/<int:pk>/delete-file-only/', views.ProgramOutcomeFileDeleteOnlyFileView.as_view(), name='delete-file-only'),

    path('upload/students/', views.populate_students, name='update-students'),
    path('upload/excempt-students/', views.handle_excempt_students, name='update-excempt-students'),
    path('recalculate-all-pos/', views.recalculate_all_pos, name='recalculate-all-pos'),
    path('create-backup-snapshot/', views.dump_pclink, name='create-backup-snapshot'),
    path('restore-pclink/', views.restore_pclink, name='restore-pclink'),
    path('remove-duplicates/', views.remove_duplicates, name='remove-duplicates'),
    path('upload/courses/', views.populate_courses_and_pos, name='populate-courses'),
    # path('upload/program-outcomes/', utils.populate_program_outcomes),
]

urlpatterns = format_suffix_patterns(urlpatterns)

pc_link_rest/urls.py
"""
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from django.contrib import admin
from django.urls import path, include, re_path
from accounts import views as account_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pc_calculator.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/503.html
{% extends 'base.html' %}
{% block content %}

<div class="text-center py-5 px-3">
    <h1>503</h1>
    <h4>Service Temporarily Unavailable</h4>
    <p>PÇ-Link is under maintenance. Try again later.</p>
</div>

{% endblock %}

templates/base.html
<!--
PÇ-Link is a report creation software for MÜDEK.
Copyright (C) 2021  Tolga ÜSTÜNKÖK

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>PÇ-Link - Student Management System for MÜDEK</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'pc_calculator/favicon.png' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'pc_calculator/css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/20d2a0c3fd.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissable fade show">
            {{ message|safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        {% block content %}
        replace me
        {% endblock %}
    </div>
    <footer class="pt-5 text-muted text-center text-small">
        <p class="mb-1">PÇ-Link Student Assessment System for MÜDEK.</p>
        <ul class="list-inline mb-1">
            <li class="list-inline-item"><a href="https://www.atilim.edu.tr/">Atılım University</a></li>
            <li class="list-inline-item"><a href="https://www.atilim.edu.tr/se/">Department of Software Engineering</a>
            </li>
            <li class="list-inline-item"><a href="mailto:tolga.ustunkok@atilim.edu.tr">Support</a></li>
        </ul>
        <p>v1.4.3</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>

</body>

</html>

templates/dashboard-base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>PÇ-Link - Student Management System for MÜDEK</title>



    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css"
        rel="stylesheet">
    <script src="https://kit.fontawesome.com/20d2a0c3fd.js" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.2/datatables.min.css"/>




    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'pc_calculator/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'pc_calculator/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'pc_calculator/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'pc_calculator/site.webmanifest' %}">
    <meta name="theme-color" content="#563d7c">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'pc_calculator/css/dashboard.css' %}" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="{% url 'pc-calc:upload' %}">PÇ-Link</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse"
            data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <ul class="navbar-nav px-3 mr-auto">
            {% if user.is_authenticated %}
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
            </li>
            {% else %}
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </nav>

    <div class="container-fluid">
        <div class="row">
            {% include 'dashboard-navbar.html' %}
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

                <div
                    class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">{% block page_title %}{% endblock %}</h1>
                </div>
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissable fade show">
                    {{ message|safe }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
                {% endif %}

                {% block content %}
                {% endblock %}
            </main>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.2/datatables.min.js"></script>
    <script src="{% static 'pc_calculator/js/dashboard.js' %}"></script>
    {% block script %}{% endblock %}
</body>

</html>

templates/dashboard-navbar.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
            <li class="nav-item">
                {% url 'pc-calc:upload' as url %}
                <a class="nav-link{% if request.path == url or request.path == '/' %} active{% endif %}" href="{% url 'pc-calc:upload' %}">
                    <span data-feather="home"></span>
                    Upload PO File <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                {% url 'pc-calc:report' as url %}
                <a class="nav-link{% if request.path == url %} active{% endif %}" href="{% url 'pc-calc:report' %}">
                    <span data-feather="bar-chart-2"></span>
                    Reports
                </a>
            </li>
            <li class="nav-item">
                {% url 'pc-calc:manage' as url %}
                <a class="nav-link{% if request.path == url %} active{% endif %}" href="{% url 'pc-calc:manage' %}">
                    <span data-feather="file"></span>
                    Manage Uploaded Files
                </a>
            </li>
        </ul>

        {% if user.is_authenticated %}
        <h6
            class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Admin Panel</span>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                {% url 'profile' as url %}
                <a class="nav-link{% if request.path == url %} active{% endif %}" href="{% url 'profile' %}">
                    <span data-feather="file-text"></span>
                    Profile
                </a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">
                    <span data-feather="file-text"></span>
                    Admin
                </a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
        <h6
            class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Build v2.2.6-<a href="https://github.com/tustunkok/pc-link/commit/{{ latest_commit }}">{{ latest_commit }}</a></span>
        </h6>
        <ul class="nav flex-column">
            <li class="nav-item">
                {% url 'pc-calc:changelog' as url %}
                <a class="nav-link{% if request.path == url %} active{% endif %}" href="{% url 'pc-calc:changelog' %}">
                    <span data-feather="shopping-cart"></span>
                    What's New?
                </a>
            </li>
            {% if user.is_authenticated and user.is_superuser %}
            {% url 'pc-calc:logs' as url %}
            <li class="nav-item">
                <a class="nav-link{% if request.path == url %} active{% endif %}" href="{% url 'pc-calc:logs' %}">
                    <span data-feather="shopping-cart"></span>
                    Logs
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/navbar.html
<nav class="navbar navbar-light navbar-expand-md mb-3">
    <div class="container">
        <a class="navbar-brand" href="{% url 'pc-calc:home' %}">
            <span style="font-size: 26px;">PÇ-Link</span> <span style="font-size: 12px;">by Department of Software
                Engineering</span>
        </a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle
                navigation</span><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="nav navbar-nav text-left ml-auto">
                {% url 'pc-calc:upload' as url %}
                <li class="nav-item{% if request.path == url %} active{% endif %}" role="presentation"><a
                        class="nav-link" href="{% url 'pc-calc:upload' %}">Upload PO
                        File</a></li>

                {% url 'pc-calc:report' as url %}
                <li class="nav-item{% if request.path == url %} active{% endif %}" role="presentation"><a
                        class="nav-link" href="{% url 'pc-calc:report' %}">Create
                        Report</a>
                </li>

                {% url 'pc-calc:manage' as url %}
                <li class="nav-item{% if request.path == url %} active{% endif %}" role="presentation"><a
                        class="nav-link" href="{% url 'pc-calc:manage' %}">Manage
                        Uploaded
                        Files</a></li>

                {% url 'pc-calc:changelog' as url %}
                <li class="nav-item{% if request.path == url %} active{% endif %}" role="presentation"><a
                        class="nav-link" href="{% url 'pc-calc:changelog' %}">What's New?</a>
                </li>
                {% if user.is_authenticated %}
                {% url 'profile' as url %}
                <li class="nav-item{% if request.path == url %} active{% endif %}" role="presentation"><a
                        class="nav-link" href="{% url 'profile' %}">Profile</a></li>
                {% if user.is_superuser %}
                <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                {% endif %}
                <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>